-- require("hardtime").setup({
--     disabled_keys = {
--         ["<Up>"] = {},
--         ["<Down>"] = {},
--         ["<Left>"] = {},
--         ["<Right>"] = {},
--     },
--     max_count = 3,
--     allow_different_key = true,
--     disable_mouse = false,
--     disabled_filetypes = { "qf", "netrw", "NvimTree", "lazy", "mason", "harpoon", "undotree" },
-- })
